name: Flet Android Production Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet
          # Eğer requirements.txt varsa: pip install -r requirements.txt

      - name: Setup Java (Android SDK için gerekli)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Signed APK
        run: |
          flet build apk --no-interactive
        env:
          FLET_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          FLET_ANDROID_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          FLET_ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: FletApp-Production
          path: build/apk/*.apk